version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: career-advisor-db
    environment:
      POSTGRES_DB: CareerAdvisorDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: career-advisor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

  ai-service:
    build:
      context: ./ai-service
    container_name: career-advisor-ai
    ports:
      - "8001:8001"
    restart: unless-stopped

volumes:
  postgres_data:
